version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${BACKEND_PORT_HOST}:${BACKEND_PORT}
    volumes:
      - ./:/app
      - node_modules_volume:/app/node_modules
    depends_on:
      - db
    environment: # <------ Add this section to pass environment variables
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT_HOST: ${POSTGRES_PORT_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      BACKEND_PORT_HOST: ${BACKEND_PORT_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT_HOST}:${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  node_modules_volume:
