# docker-compose.yml
version: 'latest'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:3000
    volumes:
      - ./:/app
      - node_modules_volume:/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - 54320:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d admin"]
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  node_modules_volume: