# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      
      - name: Start services using Docker Compose
        run: docker-compose -p chatbackend -f docker-compose.dev.yml up --build -d
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT_HOST: ${{ secrets.POSTGRES_PORT_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          BACKEND_PORT_HOST: ${{ secrets.BACKEND_PORT_HOST }}
          BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}

      - name: List running containers
        run: docker ps

      - name: Compare environment variables
        run: |
          [ "${{ secrets.POSTGRES_DB }}" == "admin" ] && echo "POSTGRES_DB: true" || echo "POSTGRES_DB: false"
          [ "${{ secrets.POSTGRES_USER }}" == "root" ] && echo "POSTGRES_USER: true" || echo "POSTGRES_USER: false"
          [ "${{ secrets.POSTGRES_PASSWORD }}" == "root" ] && echo "POSTGRES_PASSWORD: true" || echo "POSTGRES_PASSWORD: false"
          [ "${{ secrets.POSTGRES_PORT_HOST }}" == "54320" ] && echo "POSTGRES_PORT_HOST: true" || echo "POSTGRES_PORT_HOST: false"
          [ "${{ secrets.POSTGRES_PORT }}" == "5432" ] && echo "POSTGRES_PORT: true" || echo "POSTGRES_PORT: false"
          [ "${{ secrets.POSTGRES_HOST }}" == "db" ] && echo "POSTGRES_HOST: true" || echo "POSTGRES_HOST: false"
          [ "${{ secrets.BACKEND_PORT_HOST }}" == "8000" ] && echo "BACKEND_PORT_HOST: true" || echo "BACKEND_PORT_HOST: false"
          [ "${{ secrets.BACKEND_PORT }}" == "3000" ] && echo "BACKEND_PORT: true" || echo "BACKEND_PORT: false"
          [ "${{ secrets.JWT_SECRET }}" == "SECRET_KEY" ] && echo "JWT_SECRET: true" || echo "JWT_SECRET: false"
          [ "${{ secrets.JWT_EXPIRATION_TIME }}" == "60m" ] && echo "JWT_EXPIRATION_TIME: true" || echo "JWT_EXPIRATION_TIME: false"
      
      
          
      - name: Execute tests inside the container
        run: docker exec chatbackend_backend_1 sh -c "npm i -g @nestjs/cli && npm i && npm test && npm run test:e2e"
      

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: https://npm.pkg.github.com/
      - run: npm i -g @nestjs/cli
      - run: npm i
      - run: npm run build:lib
      - run: npm run pack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
